### ISSUE TITLE
Herschrijf les functies/voorschrift

### ISSUE THREAD

**Issue by florisdf** [florisdf/hoe-zit-het#35]
Deze les kreeg veel negatieve feedback via Google Analytics. Dringend eens herschrijven dus!

**Comment by PrincepsMaximus** [comment]
Op regel 64 staat: "$$\green{y} = 5\cdot {x}^0$**%**". Ik vermoed dat de **%** hier een **$** moet zijn om goed weergegeven te worden.

**Comment by florisdf** [comment]
Woeps! Schrijffoutje inderdaad! Bedankt om dit op te merken.

Net gefikst (https://github.com/hoezithet/hoezithet/commit/96826745d6f806a29324ed6709925913fead4cce)
